Implemented hours object
VikeLabs/uvic-course-scraper pull request #83
Opened 2021-02-09 03:18 UTC by shergillmanav19

Changed formatting from hoursToCatalog: string to hoursToCatalog: {lecutre:string , lab:string, tutorial:string}

2021-02-10 05:43 UTC, keithradford commented on src/index.ts
> +  if (typeof courseDetails.hoursCatalogText === 'string') {
Do we know that `hoursCatalogText` is always going to exist? I know the `KualiCourseItem` type has it as an optional attribute, so it might be worth checking in the if statement if `course.Details.hourCatalogText` exists prior to checking it's type and doing stuff with it.

2021-02-10 05:43 UTC, keithradford commented on src/index.ts
>    courseDetails.description = courseDetails.description.replace(/(<([^>]+)>)/gi, '');
Might be worth leaving a comment before the if statement, could be unclear what's going on

2021-02-10 05:43 UTC, keithradford commented on src/index.ts
> +const main = async () => {
Don't forget to remove this

2021-02-10 05:43 UTC, keithradford commented on src/types.ts
> +  [x: string]: any;
What's this here for?

2021-02-10 05:43 UTC, keithradford commented on src/types.ts
> +  //This has two types because the ones returned from uvic is a
Just as a small nit I'd move this comment to be before the new type you defined instead of in the middle of this type

2021-02-10 05:43 UTC, keithradford commented on src/index.ts
> +    const temp: string[] | undefined = hours.split('-');
Pretty sure you can replace `string[] | undefined` with just `string[]`. This should fix some linting errors too.

2021-02-10 05:43 UTC, keithradford commented on src/types.ts
>  export interface KualiCourseItem extends KualiCourseCatalog {
Maybe it would make sense if this type was called something like `ParsedKualiCourse` and then the new type can be `KualiCourseItem`, then the naming of the types helps clear up what's happening.

2021-02-10 05:43 UTC, keithradford commented on src/index.ts
> +    return courseDetailsWithHours;
I think this functionality (everything in the if statement) would be better off in the API method itself. The purpose of `fetchCourseDetails` should just do the ripping from kuali, and the method can make some changes to the parsed data if that makes sense.

2021-02-10 05:47 UTC, shergillmanav19 commented on src/index.ts
> +  if (typeof courseDetails.hoursCatalogText === 'string') {
if it doesnt exist then its type is going to be 'undefined' wont it? so it will never go in the if statement if it doesnt exist

2021-02-10 05:48 UTC, shergillmanav19 commented on src/index.ts
>    courseDetails.description = courseDetails.description.replace(/(<([^>]+)>)/gi, '');
yep will do that

2021-02-10 05:48 UTC, shergillmanav19 commented on src/index.ts
> +const main = async () => {
hahah my bad

2021-02-10 05:48 UTC, shergillmanav19 commented on src/types.ts
> +  [x: string]: any;
no clue, i never typed that idk how it got here

2021-02-10 05:49 UTC, shergillmanav19 commented on src/types.ts
> +  //This has two types because the ones returned from uvic is a
kk

2021-02-10 05:49 UTC, shergillmanav19 commented on src/index.ts
> +    const temp: string[] | undefined = hours.split('-');
kk

2021-02-10 05:49 UTC, keithradford commented on src/index.ts
> +  if (typeof courseDetails.hoursCatalogText === 'string') {
Right but you're performing operations on `courseDetails.hoursCatalogText` such as split anyways so you should probably be checking it exists

2021-02-10 05:50 UTC, shergillmanav19 commented on src/index.ts
> +    return courseDetailsWithHours;
but we're already doing stripping html tags from the parsed data might as well have this there? instead of playing around with parsed data in two different methods? up to you tho I will change

2021-02-10 05:52 UTC, keithradford commented on src/index.ts
> +    return courseDetailsWithHours;
This is a bit more dramatic of a change than stripping HTML tags, but tbh you got a point, we could just move the regex too.

2021-02-10 05:53 UTC, aomi commented on src/index.ts
> +    return courseDetailsWithHours;
I think it's fine to leave this here as we don't have a place that does any Kuali specific stuff. Maybe add a TODO to mention move these to a Kuali specific extract function (like what we're doing with BAN1P)

2021-02-10 05:53 UTC, keithradford commented on src/index.ts
> +  if (typeof courseDetails.hoursCatalogText === 'string') {
also it might be nice for clean code since you eventually say `const hours = courseDetails.hoursCatalogText`, you might as well do that before the if statement so you can just say `if(typeof hours === ....)`

2021-02-13 03:54 UTC, keithradford approved these changes

2021-02-13 03:54 UTC, keithradford commented on src/index.ts
> +  ): Promise<ParsedKualiCourse> => {
Is it possible for this return type to be `Promise<KualiCourseItem>`?  I'd rather us be returning to the user that because that's the type that's guaranteed to have hours as an object. If that causes an error, then can you change in the README where it says that this function "Returns a `KualiCourseItem` object with details for the course" to have the updated type name?

2021-02-13 03:54 UTC, keithradford commented
LGTM aside from the one comment. It makes more sense to be returning a type `KualiCourseItem`, just sounds nicer.

2021-02-13 04:50 UTC, keithradford approved these changes

2021-02-13 14:57 UTC, isaaccormack commented on src/index.ts
> +  //TODO: move these to a Kuali specific extract function (like what we're doing with BAN1P)
why not do this in this PR?

2021-02-13 15:12 UTC, isaaccormack requested changes

2021-02-13 15:12 UTC, isaaccormack commented on src/types.ts
> +export interface KualiCourseItem extends ParsedKualiCourse {
Why is this as a superclass? I'm not seeing how this use case lends itself to this design pattern. This is adding a lot of confusion wrt the intent of the code imo.

Also, none of the files in dev/ were changed and therefore are using the new KualiCourseItem, is this intended? 

I see that ParsedKualiCourse type has a field hoursCatalogText of type string or { lectrue ...}. Is there a reason why it isn't sufficient to get rid of the 'string | ' part of that type and call it a day? I feel like I'm missing something here...

2021-02-14 02:35 UTC, shergillmanav19 commented on src/index.ts
> +  //TODO: move these to a Kuali specific extract function (like what we're doing with BAN1P)
not too sure haha Aomi said to do it later

2021-02-14 15:03 UTC, isaaccormack commented
I thought we were getting rid of the superclass?

2021-02-15 23:06 UTC, isaaccormack approved these changes
LGTM

2021-02-15 23:06 UTC, merged